orbs:
  aws-cli: circleci/aws-cli@2.1.0
version: 2.1
jobs:
  build:
    docker:
      -image:cimg/openjdk:14
    steps:
      -checkout
      -run:gradle build
workflows:
  jobsequence:
    jobs:
      -build
